---
apiVersion: v1
kind: ConfigMap
metadata:
  name: CLUSTER_NAME-static-config
  namespace: traefikee
data:
  static.toml: |
    [entryPoints]
      [entryPoints.web]
        address = ":80"
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

      [entryPoints.websecure]
        address = ":443"

    [api]
      dashboard = true

    [providers.kubernetesCRD]


    [certificatesResolvers.default.acme]
      email = "LE_EMAIL"
      [certificatesResolvers.default.acme.tlschallenge]

    [authSources]
      [authSources.microsoft.oidc]
        issuer = "https://sts.windows.net/AZURE_TENANT_ID/"
        clientID = "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
        clientSecret = "random_password"

